// Proxy re-export for the autogenerated Supabase client
// This keeps frontend imports using the @ alias working with Vite config (alias @ -> client/src)

export { supabase } from "../../../../src/integrations/supabase/client";
