
export const ROLES = {
    SUPERADMIN: 'SUPERADMIN',
    ADMIN: 'ADMIN',
    OPERATOR: 'OPERATOR',
    VIEWER: 'VIEWER'
};

export const MODULES = {
    CRM: 'crm',
    FINANCIAL: 'financial',
    WHATSAPP: 'whatsapp',
    SETTINGS: 'settings',
    CAMPAIGNS: 'campaigns'
};

export const ACTIONS = {
    READ: 'read',
    WRITE: 'write',
    DELETE: 'delete',
    EXECUTE: 'execute'
};

export const DEFAULT_PERMISSIONS = {
    [ROLES.ADMIN]: {
        [MODULES.CRM]: [ACTIONS.READ, ACTIONS.WRITE, ACTIONS.DELETE],
        [MODULES.FINANCIAL]: [ACTIONS.READ, ACTIONS.WRITE, ACTIONS.DELETE],
        [MODULES.WHATSAPP]: [ACTIONS.READ, ACTIONS.WRITE, ACTIONS.DELETE],
        [MODULES.SETTINGS]: [ACTIONS.READ, ACTIONS.WRITE],
        [MODULES.CAMPAIGNS]: [ACTIONS.READ, ACTIONS.WRITE, ACTIONS.EXECUTE]
    },
    [ROLES.OPERATOR]: {
        [MODULES.CRM]: [ACTIONS.READ, ACTIONS.WRITE],
        [MODULES.WHATSAPP]: [ACTIONS.READ, ACTIONS.WRITE],
        [MODULES.FINANCIAL]: [ACTIONS.READ],
        [MODULES.SETTINGS]: [], // No access
        [MODULES.CAMPAIGNS]: [ACTIONS.READ, ACTIONS.WRITE]
    },
    [ROLES.VIEWER]: {
        [MODULES.CRM]: [ACTIONS.READ],
        [MODULES.FINANCIAL]: [ACTIONS.READ],
        [MODULES.WHATSAPP]: [ACTIONS.READ],
        [MODULES.SETTINGS]: [],
        [MODULES.CAMPAIGNS]: [ACTIONS.READ]
    }
};
